name: imgpress
summary: imgpress
  A utility for encoding and compressing images for optimal web use.
adopt-info: imgpress
grade: stable
base: core18
confinement: strict
architectures:
  - build-on: [amd64, arm64, armhf]

parts:
  imgpress:
    plugin: python
    python-version: python3
    source: .
    parse-info: [setup.py]

apps:
  imgpress:
    command: bin/imgpress
    plugs:
      - home
